### ISSUE TITLE
import fails with :batch_size option

### ISSUE THREAD

**Issue by abhichvn** [keeguon/activerecord-import-oracle_enhanced#1]
```
u = [ user, user ]
User.import(u, batch_size: 1)
```

**expected:** Should add users with 2 SQL statement
**Actual:** It executes 2 statements, first is executed successfully but second one throws error as invalid statement

Results:

> User Create Many Without Validations Or Callbacks (28.0ms)[0m  [1mINSERT ALL INTO "USERS" ("ID","P_ID","S_ID","O_ID","O_TYPE","ENCRYPTED_VALUE","CREATED_AT","UPDATED_AT") VALUES (NULL,1,1,1,'User',NULL,TO_DATE('2018-03-11 07:11:21','YYYY-MM-DD HH24:MI:SS')) SELECT * FROM dual
> 
> User Create Many Without Validations Or Callbacks (41.0ms)[0m  INSERT ALL false (NULL,1,1,1,'User',NULL,TO_DATE('2018-03-11 07:11:21','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2018-03-11 07:11:21','YYYY-MM-DD HH24:MI:SS')) SELECT * FROM dual
> ActiveRecord::StatementInvalid: Java::JavaSql::SQLSyntaxErrorException: ORA-00905: missing keyword
> : INSERT ALL false (NULL,1,1,1,'User',NULL,TO_DATE('2018-03-11 07:11:21','YYYY-MM-DD HH24:MI:SS'),TO_DATE('2018-03-11 07:11:21','YYYY-MM-DD HH24:MI:SS')) SELECT * FROM dual

**Comment by keeguon** [comment]
@abhichvn Thanks, I did some changes last week, I'll have a look at this batch_size option and run some tests.

**Comment by keeguon** [comment]
@abhichvn I can confirm this has been fixed by the patches I did last week and the latest available (0.1.5) gem on rubygems fixes this problem.

**Comment by abhichvn** [comment]
@keeguon Thanks, I have verified issue with  (0.1.5) and it is working fine
