### ISSUE TITLE
support activerecord-import 1.13

### ISSUE THREAD

**Issue by geekeren** [keeguon/activerecord-import-oracle_enhanced#2]
Hi, Félix Bellanger!  
I am developing an ancient project with Rails 3.1.12 and it's hard to upgrade 3.1.12, So I must choose Activerecord-import 0.13, but now activerecord-import-oracle_enhanced only support Activerecord-import 0.18+, could you release a gem supporting 0.13 if there are no too much the code  to change.

Thank you much!

**Comment by keeguon** [comment]
@geekeren sorry I was on holidays, did you figure something out?

**Comment by geekeren** [comment]
@keeguon I have already give up the active-import, and it should take a big effort to upgrade our tech stacks.

**Comment by keeguon** [comment]
@geekeren oh sad to hear. In any case if you ever need advice to bulk import stuff in Oracle feel free to ask a coworker and I are pretty much spending our time banging our heads making AR queries compatible for anything that is not MySQL or PostgreSQL.
